services:
  - type: web
    name: splitsmart-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
